### ISSUE TITLE
Specs failing

### ISSUE THREAD

**Issue by Nerajno** [learn-co-curriculum/pfwtfp-practice-with-array-characters-lab#1]
The final 2 specs in this exercise is failing the asked requirements as it is copied code from the previous exercise.

**Comment by sgharms** [comment]
Hello, @Nerajno I was not able to duplicate this problem.

As of commit 75c53b6d821 on the solution branch, I was able to run the code and pass all the tests.

![image](https://user-images.githubusercontent.com/50019/59050094-7fd97200-8857-11e9-9a8b-0df24c15d110.png)

I'm closing this pending your reply. Let me know if you can duplicate the issue.
